// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Api.Data;

#nullable disable

namespace ProductCatalog.Api.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260108021841_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ProductCatalog.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 8, 2, 18, 41, 427, DateTimeKind.Utc).AddTicks(5995),
                            Description = "High-performance laptop for development",
                            Name = "Laptop",
                            Price = 1299.99m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 8, 2, 18, 41, 427, DateTimeKind.Utc).AddTicks(5997)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 1, 8, 2, 18, 41, 427, DateTimeKind.Utc).AddTicks(6003),
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2026, 1, 8, 2, 18, 41, 427, DateTimeKind.Utc).AddTicks(6003)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 1, 8, 2, 18, 41, 427, DateTimeKind.Utc).AddTicks(6005),
                            Description = "RGB mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 149.99m,
                            StockQuantity = 75,
                            UpdatedAt = new DateTime(2026, 1, 8, 2, 18, 41, 427, DateTimeKind.Utc).AddTicks(6005)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
